version: "2"
services:

  spark-master:
    image: spark-docker
    command: /usr/local/spark/bin/spark-class org.apache.spark.deploy.master.Master -h master
    hostname: master
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040  # Job Spark WebUI
      - 6066:6066  # Standalone Rest Server
      - 7077:7077  # Shuffle server
      - 8080:8080  # MasterWeb UI 
    volumes:
      - ./conf/master:/conf
      - spark-events:/tmp/spark-events
      - ./:/root/workshop-spark
      
  spark-worker-base:
    image: spark-docker
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_PUBLIC_DNS: localhost
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    volumes:
      - ./conf/worker:/conf
      - spark-events:/tmp/spark-events
      - ./:/root/workshop-spark

  spark-worker-1:
    extends: spark-worker-base
    hostname: worker1
    command: /usr/local/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      SPARK_WORKER_WEBUI_PORT: 8082
    links:
      - spark-master
    ports:
      - 8082:8082

  spark-worker-2:
    extends: spark-worker-base
    hostname: worker2
    command: /usr/local/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      SPARK_WORKER_WEBUI_PORT: 8083
    links:
      - spark-master
    ports:
      - 8083:8083

  history-server:
    image: spark-docker
    command: /usr/local/spark/bin/spark-class org.apache.spark.deploy.history.HistoryServer
    hostname: history
    environment:
      SPARK_CONF_DIR: /conf
    expose:
      - 18080
    ports:
      - 18080:18080
    volumes:
      - ./conf/history:/conf 
      - spark-events:/tmp/spark-events

volumes:
 spark-events:
